project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "MIMIC 4"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: documentation/index.qmd
        text: Documentation

      - href: log.qmd
        text: Log

    right: 
      - icon: github
        href: https://github.com/andreaczhang/mimic4
        
format:
  html:
    theme: flatly
    # css: styles.css
    toc: true

